import { useLocale } from "next-intl"


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({ children, params }) {
  const locale = useLocale();

  // const initialLanguage = localStorage.getItem(locale) || "vi";
  console.log(locale);
  console.log(params);
  return (
    <html lang={locale}>
      <body >{children}</body>
    </html>
  )
}
